server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.98.60.238:3306/coffsty
    username: root
    password: Dlj20000102@Dlj
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.dlj.blog.*    #springbean监控
      filter: #sql监控
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

      stat-view-servlet: #监控页配置
        enabled: true
        login-username: dljdlj
        login-password: Dlj123456
        reset-enable: fasle
        allow:

      web-stat-filter: #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,/druid/'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  level:
    root: info
  file:
    name: BlogLog.log


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.dlj.blog.entity,com.dlj.blog.pojo
  configuration:
    map-underscore-to-camel-case: true
